# Generated by Django 5.1.3 on 2024-11-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='department',
        ),
        migrations.AddField(
            model_name='react',
            name='employee',
            field=models.CharField(default='Default Employee', max_length=30),
        ),
    ]
