# Generated by Django 5.1.3 on 2024-11-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_react_department_react_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='department',
            field=models.CharField(default='Default Department', max_length=200),
        ),
        migrations.AlterField(
            model_name='react',
            name='employee',
            field=models.CharField(max_length=30),
        ),
    ]
